<?xml version="1.0" encoding="utf-8"?><Database Name="INSTITUTO_IDIOMAS" Class="InstitutoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-1CB92NJ\SQLEXPRESS;Initial Catalog=INSTITUTO_IDIOMAS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="INSTITUTO_IDIOMASConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.administrativo" Member="administrativo">
    <Type Name="administrativo">
      <Column Name="id_admin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_programa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cargo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="departamento" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="programa_administrativo" Member="programa" ThisKey="id_programa" OtherKey="id_programa" Type="programa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.agendar_clase" Member="agendar_clase">
    <Type Name="agendar_clase">
      <Column Name="id_agenda" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_estudiante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso_abierto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_profesor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_leccion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="hora" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="curso_abierto_agendar_clase" Member="curso_abierto" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="curso_abierto" IsForeignKey="true" />
      <Association Name="estudiante_agendar_clase" Member="estudiante" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="estudiante" IsForeignKey="true" />
      <Association Name="profesor_agendar_clase" Member="profesor" ThisKey="id_profesor" OtherKey="id_profesor" Type="profesor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.asistencia" Member="asistencia">
    <Type Name="asistencia">
      <Column Name="id_asistencia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_curso_abierto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_estudiante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_asistencia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="presente" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="curso_abierto_asistencia" Member="curso_abierto" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="curso_abierto" IsForeignKey="true" />
      <Association Name="estudiante_asistencia" Member="estudiante" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="estudiante" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aulas" Member="aulas">
    <Type Name="aulas">
      <Column Name="id_aula" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_programa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="capacidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="programa_aulas" Member="programa" ThisKey="id_programa" OtherKey="id_programa" Type="programa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.curso" Member="curso">
    <Type Name="curso">
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_programa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="curso" Member="curso1" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="precio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="total_horas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="curso_curso_abierto" Member="curso_abierto" ThisKey="id_curso" OtherKey="id_curso" Type="curso_abierto" />
      <Association Name="programa_curso" Member="programa" ThisKey="id_programa" OtherKey="id_programa" Type="programa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.curso_abierto" Member="curso_abierto">
    <Type Name="curso_abierto">
      <Column Name="id_curso_abierto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_curso" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_profesor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hora_inicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hora_fin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dia" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="curso_abierto_agendar_clase" Member="agendar_clase" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="agendar_clase" />
      <Association Name="curso_abierto_asistencia" Member="asistencia" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="asistencia" />
      <Association Name="curso_abierto_matricula" Member="matricula" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="matricula" />
      <Association Name="curso_curso_abierto" Member="curso" ThisKey="id_curso" OtherKey="id_curso" Type="curso" IsForeignKey="true" />
      <Association Name="profesor_curso_abierto" Member="profesor" ThisKey="id_profesor" OtherKey="id_profesor" Type="profesor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.estudiante" Member="estudiante">
    <Type Name="estudiante">
      <Column Name="id_estudiante" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cedula" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(55) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="estudiante_agendar_clase" Member="agendar_clase" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="agendar_clase" />
      <Association Name="estudiante_asistencia" Member="asistencia" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="asistencia" />
      <Association Name="estudiante_matricula" Member="matricula" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="matricula" />
    </Type>
  </Table>
  <Table Name="dbo.feriados" Member="feriados">
    <Type Name="feriados">
      <Column Name="id_feriado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="motivo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.matricula" Member="matricula">
    <Type Name="matricula">
      <Column Name="id_matricula" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_estudiante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_curso_abierto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="costo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="matricula_pagos" Member="pagos" ThisKey="id_matricula" OtherKey="id_matricula" Type="pagos" />
      <Association Name="curso_abierto_matricula" Member="curso_abierto" ThisKey="id_curso_abierto" OtherKey="id_curso_abierto" Type="curso_abierto" IsForeignKey="true" />
      <Association Name="estudiante_matricula" Member="estudiante" ThisKey="id_estudiante" OtherKey="id_estudiante" Type="estudiante" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.pagos" Member="pagos">
    <Type Name="pagos">
      <Column Name="id_pago" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_matricula" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="monto_restante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="pagos_registro_pagos" Member="registro_pagos" ThisKey="id_pago" OtherKey="id_pago" Type="registro_pagos" />
      <Association Name="matricula_pagos" Member="matricula" ThisKey="id_matricula" OtherKey="id_matricula" Type="matricula" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.profesor" Member="profesor">
    <Type Name="profesor">
      <Column Name="id_profesor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cedula" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="correo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sueldo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idioma" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="profesor_agendar_clase" Member="agendar_clase" ThisKey="id_profesor" OtherKey="id_profesor" Type="agendar_clase" />
      <Association Name="profesor_curso_abierto" Member="curso_abierto" ThisKey="id_profesor" OtherKey="id_profesor" Type="curso_abierto" />
    </Type>
  </Table>
  <Table Name="dbo.programa" Member="programa">
    <Type Name="programa">
      <Column Name="id_programa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="programa_administrativo" Member="administrativo" ThisKey="id_programa" OtherKey="id_programa" Type="administrativo" />
      <Association Name="programa_aulas" Member="aulas" ThisKey="id_programa" OtherKey="id_programa" Type="aulas" />
      <Association Name="programa_curso" Member="curso" ThisKey="id_programa" OtherKey="id_programa" Type="curso" />
    </Type>
  </Table>
  <Table Name="dbo.registro_pagos" Member="registro_pagos">
    <Type Name="registro_pagos">
      <Column Name="id_registro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_pago" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_pago" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="medio_pago" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="pagos_registro_pagos" Member="pagos" ThisKey="id_pago" OtherKey="id_pago" Type="pagos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.usuario" Member="usuario">
    <Type Name="usuario">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre_user" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="contrasennia" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>